[phases.setup]
nixPkgs = ['nodejs_20', 'postgresql', 'python311Full']

[phases.install]
cmds = ['npm ci', 'python3 -m ensurepip --upgrade', 'python3 -m pip install --break-system-packages earnings==1.1.0']

[start]
cmd = 'node src/index.js'
